sdk.version=3.4.1
SpecialCharacter= "Invalid {0}, The {0} should only contain alphanumeric characters, and special characters (''!@#$%&*_'' including the symbol for ''ampersand'' and ''less than'' ) are not allowed" 
specialCharacterRegex= [!@#$%&*_<]


